### ISSUE TITLE
Not work on android

### ISSUE THREAD

**Issue by davidgvf** [YanYuanFE/react-native-signature-canvas#371]
When you swipe to make the signature, it only draws a dot

RN version 0.76.1
react-native-signature-canvas version 4.7.2

```
const SharedSignatureCanvas = (props: SharedSignatureCanvasProps) => {
    const ref = useRef<SignatureViewRef>(null);

    const [isReady, setIsReady] = useState(false);

    useEffect(() => {
        const preloadTimeout = setTimeout(() => setIsReady(true), 500);

        return () => clearTimeout(preloadTimeout);
    }, []);

    const handleSignature = (signatureParam: string) => {
        props.handleSignature(signatureParam);
    };

    const readSignature = () => {
        if (ref.current) {
            ref.current.readSignature();
        }
    };

    const imgWidth = '100%';
    const imgHeight = '100%';
    const style = `
    .m-signature-pad {
        border: 0px #fff;
        position: absolute;
        width: ${Dimensions.get('window').width}px;
        margin: auto;
        top: 0;
        background-color: #fff;
        box-shadow: 0 1px 4px rgba(0, 0, 0, 0.27), 0 0 40px rgba(0, 0, 0, 0.08) inset;
        overflow: hidden;
    }
    .m-signature-pad--body {
        border: none;
    }
    .m-signature-pad--footer {
        display: none;
        margin: 0px;
        padding: 0px;
    }
    body, html {
        width: ${imgWidth}px;
        height: ${imgHeight}px;
    }
`;

    if (!isReady) {
        return (
            <WebView
                source={{ html: '<html lang="es"><body></body></html>' }}
                style={{ width: 0, height: 0 }} // Invisible
            />
        );
    }

    return (
        <View style={{ flex: 1, minHeight: 250 }}>
            <SignatureScreen
                ref={ref}
                key={'ex-1-sign'}
                onOK={handleSignature}
                webStyle={style}
                onEnd={readSignature}
                style={{ borderColor: '#0066BD', borderWidth: 1 }}
            />
        </View>
    );
};
```

**Comment by brunossaless** [comment]
news?

**Comment by hayder-nexgen** [comment]
any update?

**Comment by davidgvf** [comment]
Not wroked for me because my signature canva was wrap into touchablewithoutfeedback

**Comment by remacr** [comment]
I was running into the same issue using RN 0.76.5 with the new arch enabled. The problem also relies on`react-native-webview@13.13.2`, which is still not ready to run on the new architecture. If you check the LogCat of your app when you start drawing into the component, you should see the error pointing to the WebView not using the main thread to post the messages. Therefore, the internal commands (BEGIN, END ....etc) can't be read in the RN layer.

```
java.lang.Throwable: A WebView method was called on thread 'JavaBridge'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 1) {37fd6bf} called on Looper (JavaBridge, tid 563) {952c249}, FYI main Looper is Looper (main, tid 1) {37fd6bf})
                                                                                                    	at android.webkit.WebView.checkThread(WebView.java:2350)
                                                                                                    	at android.webkit.WebView.getUrl(WebView.java:1427)
                                                                                                    	at com.reactnativecommunity.webview.RNCWebView$RNCWebViewBridge.postMessage(RNCWebView.java:458)
                                                                                                    	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                                                                    	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loop(Looper.java:154)
```


Here is the solution, first add a safe check to `react-native-signature-canvas/h5/js/app.js` to only call `window.ReactNativeWebView.postMessage` when it exists: 

I created the following diff with `npx patch-package react-native-signature-canvas`
```
diff --git a/node_modules/react-native-signature-canvas/h5/js/app.js b/node_modules/react-native-signature-canvas/h5/js/app.js
index e4690cd..551a4f0 100755
--- a/node_modules/react-native-signature-canvas/h5/js/app.js
+++ b/node_modules/react-native-signature-canvas/h5/js/app.js
@@ -22,12 +22,18 @@ export default `
         imgData && signaturePad.fromData(imgData);
     }

+    function safePostMessage(data) {
+        if (window.ReactNativeWebView && window.ReactNativeWebView.postMessage) {
+            window.ReactNativeWebView.postMessage(data);
+        }
+    }
+
     window.onresize = resizeCanvas;
     resizeCanvas();

     signaturePad = new SignaturePad(canvas, {
-        onBegin: () => window.ReactNativeWebView.postMessage("BEGIN"),
-        onEnd: () => window.ReactNativeWebView.postMessage("END"),
+        onBegin: () => safePostMessage("BEGIN"),
+        onEnd: () => safePostMessage("END"),
         penColor: '<%penColor%>',
         backgroundColor: '<%backgroundColor%>',
         dotSize: <%dotSize%>,
@@ -37,50 +43,50 @@ export default `

     function clearSignature () {
         signaturePad.clear();
-        window.ReactNativeWebView.postMessage("CLEAR");
+        safePostMessage("CLEAR");
     }

     function undo() {
         signaturePad.undo();
-        window.ReactNativeWebView.postMessage("UNDO");
+        safePostMessage("UNDO");
     }

     function redo() {
         signaturePad.redo();
-        window.ReactNativeWebView.postMessage("REDO");
+        safePostMessage("REDO");
       }

     function changePenColor(color) {
         signaturePad.penColor = color;
-        window.ReactNativeWebView.postMessage("CHANGE_PEN");
+        safePostMessage("CHANGE_PEN");
     }

     function changePenSize(minW, maxW) {
       signaturePad.minWidth = minW;
       signaturePad.maxWidth = maxW;
-      window.ReactNativeWebView.postMessage("CHANGE_PEN_SIZE");
+      safePostMessage("CHANGE_PEN_SIZE");
     }

     function getData () {
         var data = signaturePad.toData();
-        window.ReactNativeWebView.postMessage(JSON.stringify(data));
+        safePostMessage(JSON.stringify(data));
     }

     function draw() {
       signaturePad.draw();
-      window.ReactNativeWebView.postMessage("DRAW");
+      safePostMessage("DRAW");
     }

     function erase() {
       signaturePad.erase();
-      window.ReactNativeWebView.postMessage("ERASE");
+      safePostMessage("ERASE");
     }

     function cropWhitespace(url) {
         var myImage = new Image();
         myImage.crossOrigin = "Anonymous";
         myImage.onload = function(){
-            window.ReactNativeWebView.postMessage(removeImageBlanks(myImage)); //Will return cropped image data
+            safePostMessage(removeImageBlanks(myImage)); //Will return cropped image data
         }
         myImage.src = url;

@@ -170,10 +176,10 @@ export default `

     function readSignature()  {
         if (signaturePad.isEmpty()) {
-            window.ReactNativeWebView.postMessage("EMPTY");
+            safePostMessage("EMPTY");
         } else {
             var url = signaturePad.toDataURL('<%imageType%>');
-            trimWhitespace? cropWhitespace(url): window.ReactNativeWebView.postMessage(url);
+            trimWhitespace ? cropWhitespace(url) : safePostMessage(url);
             if (autoClear) signaturePad.clear();
         }
     }

```

Lastly, patch the `react-native-webview` making sure it runs in the main thread. I  created the following diff with `npx patch-package react-native-webview`
```
diff --git a/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebView.java b/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebView.java
index 31cf298..af8b2a3 100644
--- a/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebView.java
+++ b/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebView.java
@@ -252,38 +252,44 @@ public class RNCWebView extends WebView implements LifecycleEventListener {
     }

     protected void createRNCWebViewBridge(RNCWebView webView) {
-        if (WebViewFeature.isFeatureSupported(WebViewFeature.WEB_MESSAGE_LISTENER)){
-          if (this.bridgeListener == null) {
-            this.bridgeListener = new WebViewCompat.WebMessageListener() {
-              @Override
-              public void onPostMessage(@NonNull WebView view, @NonNull WebMessageCompat message, @NonNull Uri sourceOrigin, boolean isMainFrame, @NonNull JavaScriptReplyProxy replyProxy) {
-                RNCWebView.this.onMessage(message.getData(), sourceOrigin.toString());
-              }
-            };
-            WebViewCompat.addWebMessageListener(
-              webView,
-              JAVASCRIPT_INTERFACE,
-              Set.of("*"),
-              this.bridgeListener
-            );
-          }
-        } else {
-          if (fallbackBridge == null) {
-            fallbackBridge = new RNCWebViewBridge(webView);
-            addJavascriptInterface(fallbackBridge, JAVASCRIPT_INTERFACE);
-          }
-        }
-        injectJavascriptObject();
+        post(() -> {
+            if (WebViewFeature.isFeatureSupported(WebViewFeature.WEB_MESSAGE_LISTENER)) {
+                if (this.bridgeListener == null) {
+                    this.bridgeListener = new WebViewCompat.WebMessageListener() {
+                        @Override
+                        public void onPostMessage(@NonNull WebView view, @NonNull WebMessageCompat message,
+                                                  @NonNull Uri sourceOrigin, boolean isMainFrame,
+                                                  @NonNull JavaScriptReplyProxy replyProxy) {
+                            RNCWebView.this.onMessage(message.getData(), sourceOrigin.toString());
+                        }
+                    };
+                    WebViewCompat.addWebMessageListener(
+                            webView,
+                            JAVASCRIPT_INTERFACE,
+                            Set.of("*"),
+                            this.bridgeListener
+                    );
+                }
+            } else {
+                if (fallbackBridge == null) {
+                    fallbackBridge = new RNCWebViewBridge(webView);
+                    addJavascriptInterface(fallbackBridge, JAVASCRIPT_INTERFACE);
+                }
+            }
+            injectJavascriptObject();
+        });
     }

     private void injectJavascriptObject() {
-      if (getSettings().getJavaScriptEnabled()) {
-        String js = "(function(){\n" +
-          "    window." + JAVASCRIPT_INTERFACE + " = window." + JAVASCRIPT_INTERFACE + " || {};\n" +
-          "    window." + JAVASCRIPT_INTERFACE + ".injectedObjectJson = function () { return " + (injectedJavaScriptObject == null ? null : ("`" + injectedJavaScriptObject + "`")) + "; };\n" +
-          "})();";
-        evaluateJavascriptWithFallback(js);
-      }
+        if (getSettings().getJavaScriptEnabled()) {
+            String js = "(function(){\n" +
+                    "    window." + JAVASCRIPT_INTERFACE + " = window." + JAVASCRIPT_INTERFACE + " || {};\n" +
+                    "    window." + JAVASCRIPT_INTERFACE + ".injectedObjectJson = function () { return " +
+                    (injectedJavaScriptObject == null ? null : ("`" + injectedJavaScriptObject + "`")) + "; };\n" +
+                    "})();";
+
+            post(() -> evaluateJavascriptWithFallback(js));
+        }
     }

     @SuppressLint("AddJavascriptInterface")
@@ -300,7 +306,7 @@ public class RNCWebView extends WebView implements LifecycleEventListener {
     }

     protected void evaluateJavascriptWithFallback(String script) {
-        evaluateJavascript(script, null);
+        post(() -> evaluateJavascript(script, null));
     }

     public void callInjectedJavaScript() {
@@ -449,7 +455,7 @@ public class RNCWebView extends WebView implements LifecycleEventListener {
         @JavascriptInterface
         public void postMessage(String message) {
             if (mWebView.getMessagingEnabled()) {
-                mWebView.onMessage(message, mWebView.getUrl());
+                post(() -> mWebView.onMessage(message, mWebView.getUrl()));
             } else {
                 FLog.w(TAG, "ReactNativeWebView.postMessage method was called but messaging is disabled. Pass an onMessage handler to the WebView.");
             }

```

**Comment by yossularko** [comment]
> I was running into the same issue using RN 0.76.5 with the new arch enabled. The problem also relies on`react-native-webview@13.13.2`, which is still not ready to run on the new architecture. If you check the LogCat of your app when you start drawing into the component, you should see the error pointing to the WebView not using the main thread to post the messages. Therefore, the internal commands (BEGIN, END ....etc) can't be read in the RN layer.
> 
> ```
> java.lang.Throwable: A WebView method was called on thread 'JavaBridge'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 1) {37fd6bf} called on Looper (JavaBridge, tid 563) {952c249}, FYI main Looper is Looper (main, tid 1) {37fd6bf})
>                                                                                                     	at android.webkit.WebView.checkThread(WebView.java:2350)
>                                                                                                     	at android.webkit.WebView.getUrl(WebView.java:1427)
>                                                                                                     	at com.reactnativecommunity.webview.RNCWebView$RNCWebViewBridge.postMessage(RNCWebView.java:458)
>                                                                                                     	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
>                                                                                                     	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
>                                                                                                     	at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                                                     	at android.os.Looper.loop(Looper.java:154)
> ```
> 
> Here is the solution, first add a safe check to `react-native-signature-canvas/h5/js/app.js` to only call `window.ReactNativeWebView.postMessage` when it exists:
> 
> I created the following diff with `npx patch-package react-native-signature-canvas`
> 
> `react-native-signature-canvas+4.7.2.patch`
> 
> diff --git a/node_modules/react-native-signature-canvas/h5/js/app.js b/node_modules/react-native-signature-canvas/h5/js/app.js
> index e4690cd..8f16939 100755
> --- a/node_modules/react-native-signature-canvas/h5/js/app.js
> +++ b/node_modules/react-native-signature-canvas/h5/js/app.js
> @@ -22,12 +22,22 @@ export default `
>          imgData && signaturePad.fromData(imgData);
>      }
>      
> +    function safePostMessage(data) {
> +        setTimeout(() => {
> +            if (window.ReactNativeWebView && window.ReactNativeWebView.postMessage) {
> +                window.ReactNativeWebView.postMessage(data);
> +            } else if (window.postMessage) {
> +                window.postMessage(data);
> +            }
> +        }, 0)
> +    }
> +
>      window.onresize = resizeCanvas;
>      resizeCanvas();
>      
>      signaturePad = new SignaturePad(canvas, {
> -        onBegin: () => window.ReactNativeWebView.postMessage("BEGIN"),
> -        onEnd: () => window.ReactNativeWebView.postMessage("END"),
> +        onBegin: () => safePostMessage("BEGIN"),
> +        onEnd: () => safePostMessage("END"),
>          penColor: '<%penColor%>',
>          backgroundColor: '<%backgroundColor%>',
>          dotSize: <%dotSize%>,
> @@ -37,50 +47,50 @@ export default `
>  
>      function clearSignature () {
>          signaturePad.clear();
> -        window.ReactNativeWebView.postMessage("CLEAR");
> +        safePostMessage("CLEAR");
>      }
>      
>      function undo() {
>          signaturePad.undo();
> -        window.ReactNativeWebView.postMessage("UNDO");
> +        safePostMessage("UNDO");
>      }
>      
>      function redo() {
>          signaturePad.redo();
> -        window.ReactNativeWebView.postMessage("REDO");
> +        safePostMessage("REDO");
>        }
>  
>      function changePenColor(color) {
>          signaturePad.penColor = color;
> -        window.ReactNativeWebView.postMessage("CHANGE_PEN");
> +        safePostMessage("CHANGE_PEN");
>      }
>  
>      function changePenSize(minW, maxW) {
>        signaturePad.minWidth = minW;
>        signaturePad.maxWidth = maxW;
> -      window.ReactNativeWebView.postMessage("CHANGE_PEN_SIZE");
> +      safePostMessage("CHANGE_PEN_SIZE");
>      }
>      
>      function getData () {
>          var data = signaturePad.toData();
> -        window.ReactNativeWebView.postMessage(JSON.stringify(data));
> +        safePostMessage(JSON.stringify(data));
>      }
>  
>      function draw() {
>        signaturePad.draw();
> -      window.ReactNativeWebView.postMessage("DRAW");
> +      safePostMessage("DRAW");
>      }
>  
>      function erase() {
>        signaturePad.erase();
> -      window.ReactNativeWebView.postMessage("ERASE");
> +      safePostMessage("ERASE");
>      }
>  
>      function cropWhitespace(url) {
>          var myImage = new Image();
>          myImage.crossOrigin = "Anonymous";
>          myImage.onload = function(){
> -            window.ReactNativeWebView.postMessage(removeImageBlanks(myImage)); //Will return cropped image data
> +            safePostMessage(removeImageBlanks(myImage)); //Will return cropped image data
>          }
>          myImage.src = url;
>  
> @@ -170,10 +180,10 @@ export default `
>  
>      function readSignature()  {
>          if (signaturePad.isEmpty()) {
> -            window.ReactNativeWebView.postMessage("EMPTY");
> +            safePostMessage("EMPTY");
>          } else {
>              var url = signaturePad.toDataURL('<%imageType%>');
> -            trimWhitespace? cropWhitespace(url): window.ReactNativeWebView.postMessage(url);
> +            trimWhitespace ? cropWhitespace(url) : safePostMessage(url);
>              if (autoClear) signaturePad.clear();
>          }
>      }
> diff --git a/node_modules/react-native-signature-canvas/index.js b/node_modules/react-native-signature-canvas/index.js
> index 7f9f0e8..12ab8af 100644
> --- a/node_modules/react-native-signature-canvas/index.js
> +++ b/node_modules/react-native-signature-canvas/index.js
> @@ -50,20 +50,20 @@ const SignatureView = forwardRef(
>        minWidth = 0.5,
>        maxWidth = 2.5,
>        nestedScrollEnabled = false,
> -      showsVerticalScrollIndicator= true,
> -      onOK = () => {},
> -      onEmpty = () => {},
> -      onClear = () => {},
> -      onUndo = () => {},
> -      onRedo = () => {},
> -      onDraw = () => {},
> -      onErase = () => {},
> -      onGetData = () => {},
> -      onChangePenColor = () => {},
> -      onChangePenSize = () => {},
> -      onBegin = () => {},
> -      onEnd = () => {},
> -      onLoadEnd = () => {},
> +      showsVerticalScrollIndicator = true,
> +      onOK = () => { },
> +      onEmpty = () => { },
> +      onClear = () => { },
> +      onUndo = () => { },
> +      onRedo = () => { },
> +      onDraw = () => { },
> +      onErase = () => { },
> +      onGetData = () => { },
> +      onChangePenColor = () => { },
> +      onChangePenSize = () => { },
> +      onBegin = () => { },
> +      onEnd = () => { },
> +      onLoadEnd = () => { },
>        overlayHeight = 0,
>        overlayWidth = 0,
>        overlaySrc = null,
> @@ -258,13 +258,22 @@ const SignatureView = forwardRef(
>        console.warn("WebView error: ", nativeEvent);
>  
>      const handleLoadEnd = () => {
> -        setLoading(false);
> -        onLoadEnd();
> +      setLoading(false);
> +      onLoadEnd();
>      }
>  
> +    // Patch to force reload the webview when using the new arch when the component has already been mount before.
> +    // It solves the infinite loading indicator issue.
> +    const [key, setKey] = useState(new Date().getTime());
> +
> +    useEffect(() => {
> +      setKey(new Date().getTime());
> +    }, []);
> +
>      return (
>        <View style={[styles.webBg, style]}>
>          <WebView
> +          key={`signature-screen-${key}`}
>            bounces={false}
>            style={[webviewContainerStyle]}
>            scrollEnabled={scrollable}
> Lastly, patch the `react-native-webview` making sure it runs in the main thread by using the View `post` method. I created the following diff with `npx patch-package react-native-webview`
> 
> `react-native-webview+13.13.2.patch`
> 
> diff --git a/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebView.java b/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebView.java
> index 31cf298..af8b2a3 100644
> --- a/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebView.java
> +++ b/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebView.java
> @@ -449,7 +455,7 @@ public class RNCWebView extends WebView implements LifecycleEventListener {
>          @JavascriptInterface
>          public void postMessage(String message) {
>              if (mWebView.getMessagingEnabled()) {
> -                mWebView.onMessage(message, mWebView.getUrl());
> +                post(() -> mWebView.onMessage(message, mWebView.getUrl()));
>              } else {
>                  FLog.w(TAG, "ReactNativeWebView.postMessage method was called but messaging is disabled. Pass an onMessage handler to the WebView.");
>              }

I'm using RN 0.76.7 and react-native-webview 13.13.2 works perfectly without applying this patch. (tested on android only)

**Comment by davidgvf** [comment]
@next6leo a mi se soluciono actualizando la lib de react native web view, ya que subieron una version con un error

**Comment by next6leo** [comment]
@davidgvf what webview version?

**Comment by davidgvf** [comment]
> @davidgvf what webview version?

With this version for me its fix

   "react-native-webview": "13.13.2"

**Comment by next6leo** [comment]
thanks @davidgvf i try install see

**Comment by next6leo** [comment]
found out is the TouchableWithoutFeedback cause it. thank you.
