### ISSUE TITLE
    Invariant Violation: nodeHandle expected to be non-null

### ISSUE THREAD

**Issue by erikhu** [YanYuanFE/react-native-signature-canvas#75]
Heyy hru? i have some issue when i am testing. i try to run the onOK throught a function, and everything is ok when a i do it on phone but when a i am testing, i get this error.

Invariant Violation: nodeHandle expected to be non-null

      63 |     const completeDelivery = () => {
    > 65 |         signature.current?.readSignature();
         |                            ^
      66 |     };

      at invariant (node_modules/invariant/invariant.js:40:15)
      at WebView.getWebViewHandle (node_modules/react-native-webview/lib/WebView.ios.js:158:13)
      at WebView.injectJavaScript (node_modules/react-native-webview/lib/WebView.ios.js:142:56)
      at Object.readSignature (node_modules/react-native-signature-canvas/index.js:82:28)

i was trying a lot of things but it was fruitless.

**Comment by YanYuanFE** [comment]
Are you using Typescript?

**Comment by erikhu** [comment]
> Are you using Typescript?

yes sr

**Comment by erikhu** [comment]
i close the issue, because i solve it with mocking and fire event onOk directly
